// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOx7avSVq1GLqrLyeTTrxsg0l4dCeSxU4',
    appId: '1:948236572037:android:4e36811ce9e48166eea0ec',
    messagingSenderId: '948236572037',
    projectId: 'aeza-flutter-test-task',
    storageBucket: 'aeza-flutter-test-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA7HFrS-M5xytdvod7ZzgkPYvv9kWjGFY',
    appId: '1:948236572037:ios:695973b19039f76beea0ec',
    messagingSenderId: '948236572037',
    projectId: 'aeza-flutter-test-task',
    storageBucket: 'aeza-flutter-test-task.firebasestorage.app',
    iosBundleId: 'com.example.aezaFlutterNew',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXaRpIFKAZubyXF9Cz31feNZI2fktZcYM',
    appId: '1:948236572037:web:4db4e5a5cfeb8c20eea0ec',
    messagingSenderId: '948236572037',
    projectId: 'aeza-flutter-test-task',
    authDomain: 'aeza-flutter-test-task.firebaseapp.com',
    storageBucket: 'aeza-flutter-test-task.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA7HFrS-M5xytdvod7ZzgkPYvv9kWjGFY',
    appId: '1:948236572037:ios:695973b19039f76beea0ec',
    messagingSenderId: '948236572037',
    projectId: 'aeza-flutter-test-task',
    storageBucket: 'aeza-flutter-test-task.firebasestorage.app',
    iosBundleId: 'com.example.aezaFlutterNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXaRpIFKAZubyXF9Cz31feNZI2fktZcYM',
    appId: '1:948236572037:web:a8eae4826895bf03eea0ec',
    messagingSenderId: '948236572037',
    projectId: 'aeza-flutter-test-task',
    authDomain: 'aeza-flutter-test-task.firebaseapp.com',
    storageBucket: 'aeza-flutter-test-task.firebasestorage.app',
  );

}